# Generated by Django 4.2.7 on 2024-01-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=255, verbose_name='Department Name')),
                ('deptdesc', models.TextField(verbose_name='Department Description')),
            ],
        ),
        migrations.AlterField(
            model_name='pataient',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.department', verbose_name='Select Department'),
            preserve_default=False,
        ),
    ]
