# Generated by Django 4.2.7 on 2024-01-20 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_department_alter_pataient_gender_doctor_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False)),
                ('appmadeon', models.DateField(auto_now_add=True, verbose_name='Appointment Made Date')),
                ('appdate', models.DateField(verbose_name='Appointment Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
