# Generated by Django 3.2.15 on 2024-02-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default=1, upload_to='dept_img/'),
            preserve_default=False,
        ),
    ]
