# Generated by Django 3.2.15 on 2023-09-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(max_length=255, verbose_name='Doctor Degree'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dname',
            field=models.CharField(max_length=200, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='yoe',
            field=models.CharField(max_length=2, verbose_name='Year of Experience'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=255, verbose_name='Available Days')),
                ('time_slot', models.CharField(max_length=200, verbose_name='Available Time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor', verbose_name='Doctor')),
            ],
        ),
    ]
